### ISSUE TITLE
Класс field file - не отрабатывает проверки обязательности в форме/фильтре

### ISSUE THREAD

**Issue by toksy** [essence-community/core-frontend#545]
Шаги: 
вставить поле с выбором файла/файлов в фильтр или форму 
указать атрибут required = true 

Ожидаемый результат: 
Система не пропустит запрос без выбранного файла (или файлов в зависимости от filemode) 

Фактический результат: 
система пропускает запросы без проверки

**Comment by Honyrik** [comment]
fix
